name: sepsis
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.6
  - pytorch
  - torchvision
  - cudatoolkit>=9.2    # mac OS users should comment out this (for CPU only) or build from the source
  - scikit-learn
  - numpy
  - pandas
  - matplotlib
  # - google-cloud-bigquery
  - pyarrow
  - pip
  - pip:
    - google-cloud-bigquery[bqstorage,pandas]